### ISSUE TITLE
Lib usage clarification

### ISSUE THREAD

**Issue by nyurik** [danieldg/futures-join-stream#1]
Hi, thanks for posting the lib. I tried to follow the logic, but got a bit lost -- is there a usage example of your lib?  I have several streams of objects, and each stream is produced by a different thread. Each stream has some ID. I need to combine all streams into one, making sure that all items from a stream with a lower ID are processed before the items from a higher-ID stream.

Stream 1:  A, B, C
Stream 2: D, E, F
Stream 3: G, H, I

Combining above streams should produce letters in alphabet order.  Note that I could have thousands of those streams, so it is better even to think of all this as a "stream of streams".

**Comment by danieldg** [comment]
The ordered-stream crate (which is what this crate has been renamed to) now has an example.  The "stream of streams" concept is not what this crate is trying to solve - that's a much simpler problem, and is solved by the `flatten` function from `futures_util`.
